services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis
    ports:
      - "6969:6969"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    ports:
      - "6970:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
